### ISSUE TITLE
loopback interface creation implemented by just returning nil in libcontainer/network/loopback.go?

### ISSUE THREAD

**Issue by allencloud** [docker/libcontainer#323]
Hi, all

The title is my confusion.

Nowadays I was reading source code of libcontainer. And I found that when starting Docker Container with bridge mode, libcontainer would create a loopback interface as well. But in libcontainer/network/loopback.go#L13-L15, the source code is like below:

func (l *Loopback) Create(n *Network, nspid int, networkState *NetworkState) error {
	return nil
}

Just return nul !

But when we tunnel into the newly started container, we can still see the loopback interface.

There must be something that made it.  And what is it? Now I cannot made it in theory.

Anything helps.

Thanks in advance.

Allen
DaoCloud, China

**Comment by LK4D4** [comment]
@allencloud I believe that it creates on network namespace creation and `libcontainer` just `UP` it.

**Comment by crosbymichael** [comment]
@allencloud 

Yes, the loopback interface is created automatically by the kernel when you create a new network namespace.  

After the kernel creates the interface all we do is bring it up leaving all the settings default.  If you want to play around you can see this by running this small snippet of go code:

```go
package main

import (
        "log"
        "os"
        "os/exec"
        "syscall"
)

func main() {
        // run the ip command to list the interfaces
        cmd := exec.Command("ip", "a")
        cmd.Stdout = os.Stdout
        cmd.Stderr = os.Stderr
        // create a new network namepsace by setting the CLONE_NEWNET flag as
        // part of the clone flags for the forked process
        cmd.SysProcAttr = &syscall.SysProcAttr{
                Cloneflags: syscall.CLONE_NEWNET,
        }
        if err := cmd.Run(); err != nil {
                log.Fatal(err)
        }
}
```

Remember you will have to run this a root on your system in order to create new network namespaces but this should demonstrate how the loopback device is created by the kernel.
