### ISSUE TITLE
Handle waiting for processes with forks

### ISSUE THREAD

**Issue by LK4D4** [docker/libcontainer#396]
Now we just waiting with `cmd.Wait`, but if there is some forks with inherited pipes - we will wait forever, so we need `cmd.Process.Wait` then kill all processes in cgroup, then `cmd.Wait` for waiting pipes copy. This probalby makes sense only for host `PID` namespace.
#349 for reference

**Comment by avagin** [comment]
I can't understand why we need to care about applications which doesn't wait its children. In a previous version we was not able to handle this situation properly. Now we can get a process PID and wait it. Maybe it's enough to not worry about this in libcontainer.

**Comment by LK4D4** [comment]
@avagin Maybe, but then main use-case(libvirt) for `--pid=host` in docker not working. I think in previous version it was solved at some point.

**Comment by LK4D4** [comment]
Btw `criu` is affected as well according to Saied.
ping @crosbymichael

**Comment by avagin** [comment]
@LK4D4  @SaiedKazemi  Why can't you do something like this? Or maybe I don't understand something...
https://github.com/avagin/libcontainer/commit/bc9f5004e8eb8bf7a308056298ae773c8f185844#diff-e7a3526322d2039a417ca9f452cbc748R66

**Comment by SaiedKazemi** [comment]
The restore code has two waits:
    1. For criu to exit (after restoring the container).
    2. For the container.
For (1), we have to use command.Process.Wait() exactly for the reason explained in #349 because criu has passed its pipes to the restored container.  Doing command.Wait() hangs until the container exits.
For (2), we use syscall.Wait4(restorePid, ...) where restorePid is the pid of the restored container reported by criu in step (1) above.

**Comment by LK4D4** [comment]
I'm closing this, because I'm not exactly sure what we can do.
