### ISSUE TITLE
Cannot create Shared bind mounts in docker

### ISSUE THREAD

**Issue by wlan0** [docker/libcontainer#466]
I tried to create shared bind mounts in docker. I did that by setting the MS_SHARED flag in the mount syscall. 

i added this line after (tried before as well and various other variants) the bind mount ( https://github.com/docker/libcontainer/blob/master/rootfs_linux.go#L111 )

```
                 if m.Flags&syscall.MS_SHARED != 0 {
                         if err := syscall.Mount("", dest, "none", uintptr(syscall.MS_REC|syscall.MS_SHARED), ""); err != nil {
                                 return err
                         }
                 }
```

But it doesn't create shared mounts. I'm testing this on ubuntu: 14.04. Is there a fundamental design decision that prevents shared mounts  that i'm missing?

**Comment by wlan0** [comment]
@mrunalp @cpuguy83 @ibuildthecloud

**Comment by ibuildthecloud** [comment]
@wlan0 This approach your doing is a bit off, but in short the shared mount will not currently work in Docker because before the pivot_root is done the equivalent of `--make-rprivate` is done on the new root.  In order to support shared and slave mounts we need to be a bit more selective about setting private on the mounts.
